#!/usr/bin/env bash

set -euo pipefail

(
    for x in "$WD/src/com"/*.hs; do
        (
            hlint "$x"
            ormolu -m inplace "$x"
        ) &
    done
    for _ in $(jobs -p); do
        wait -n
    done
    flags=(
        -dynamic
        "-fdiagnostics-color=always"
        -funbox-strict-fields
        "-i$WD/src/com"
        "-optl -fuse-ld=lld"
        "-outputdir $WD/build"
        -Wall
        -Wcompat
        -Werror
        -Widentities
        -Wincomplete-record-updates
        -Wincomplete-uni-patterns
        -Wmonomorphism-restriction
        -Wpartial-fields
        -Wredundant-constraints
        -Wunused-packages
        -Wunused-type-patterns
    )
    ghc "${flags[@]}" -o "$WD/bin/com" "$WD/src/com/Main.hs"
)
(
    flags=(
        "-ferror-limit=1"
        -ffast-math
        -fno-autolink
        -fno-exceptions
        -fno-math-errno
        -fno-omit-frame-pointer
        -fno-rtti
        -fno-unwind-tables
        "-fsanitize=address"
        "-fsanitize=undefined"
        -fshort-enums
        "-march=native"
        -O1
        "-std=c++11"
        -Werror
        -Weverything
        -Wno-c++98-compat-pedantic
        -Wno-covered-switch-default
        -Wno-extra-semi-stmt
        -Wno-padded
        -Wno-reserved-id-macro
    )
    clang-format -i -verbose "$WD/src/vm/"*
    mold -run clang++ "${flags[@]}"  -o "$WD/bin/vm" "$WD/src/vm/main.cpp"
)
(
    for x in "$WD/examples/"*.bla; do
        echo "$x"
        "$WD/bin/com" "$x" "$WD/bin/main.blc" \
            && "$WD/bin/vm" "$WD/bin/main.blc"
    done
)
